### ISSUE TITLE
Display strikethrough text with a line through it

### ISSUE THREAD

**Issue by johnblommers** [guilhermeprokisch/see#1]
`smd `will not display strikethrough text. This is not the behavior I'd expect. Most Markdown tools I've run into will display the text with a horizontal line through it like this:

~~oops~~

Consider changing the program's behavior?

**Comment by guilhermeprokisch** [comment]
Which terminal are you using? Some ansi codes are not interpreted in all of them.

**Comment by johnblommers** [comment]
> Which terminal are you using? Some ansi codes are not interpreted in all of them.

The Gnome Terminal is my default. But I see Wezterm also removes strike-through text.

Note that these strikethrough texts are in tables, so if every cell contains strikethrough text then you get a blank line. And without those vertical and horizontal table borders, it's rather confusing output.

On the other hand, I kind of get it. Strikethrough text was text  its author wanted to strike out or delete. I'm just used to seeing the text with a horizontal line through it.

**Comment by guilhermeprokisch** [comment]
@johnblommers  can you give a markdown example then I can debug it?
