### ISSUE TITLE
Which terminals support images?

### ISSUE THREAD

**Issue by johnblommers** [guilhermeprokisch/see#3]
It's not clear which terminals support `smd` rendering images.

Is there a list of tested terminals?

**Comment by guilhermeprokisch** [comment]
I've tested in Alacratty, Kitty but the safe choice that I've been got most of the features working it's was Wezterm

**Comment by guilhermeprokisch** [comment]
@johnblommers was you able run it?

**Comment by lost22git** [comment]
windows terminal support sixel now

https://github.com/microsoft/terminal/releases?q=sixel&expanded=true

**Comment by dsully** [comment]
If you're on the Ghostty beta, this PR needs to be merged, and then a new version of `viuer` released:

https://github.com/atanunq/viuer/pull/58

**Comment by dsully** [comment]
Did the version get bumped?
